/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import java.awt.BasicStroke;
import java.awt.Color;
import Classes.Company;
import Classes.ProjectManager;
import Classes.Supervisor;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import java.io.PrintWriter;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.filechooser.FileNameExtensionFilter;
 

/**
 *
 * @author kevin
 */
public class Interface extends javax.swing.JFrame {

            Company Apple = new Company("Apple", 5);
            Company MSI = new Company("MSI", 5);
            boolean iniciado=false;
            private String path;
            int max_apple = 13; //Carnet de Kevin termina en 1
            int max_msi = 15; //Carnet de Andrea termina en 3
    

    /**
     * Creates new form Ventana
     */
    public Interface() {
        initComponents();

    }
    
    public static JLabel getApple_Deadline_Counter() {
        return Apple_Deadline_Counter;
    }
    
    
     public static JLabel getMSI_Deadline_Counter() {
        return MSI_Deadline_Counter;
    }
    

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        saveButtonActionPerformed = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Cont_Deadline = new javax.swing.JSpinner();
        Cont_Day_Duration = new javax.swing.JSpinner();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Const_ProduPlaca_Apple = new javax.swing.JSpinner();
        Const_ProduCPU_Apple = new javax.swing.JSpinner();
        Const_ProduMemoRAM_Apple = new javax.swing.JSpinner();
        Const_ProduFuenteAlime_Apple = new javax.swing.JSpinner();
        Const_ProduTarjegGraf_Apple = new javax.swing.JSpinner();
        Const_Ensambladores_Apple = new javax.swing.JSpinner();
        Apple_Director_State = new javax.swing.JLabel();
        Apple_Pm_State = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Apple_Fail_Counter = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Apple_Discount_Counter = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Apple_Deadline_Counter = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Apple_Gain_Counter = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Apple_Loss_Counter = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Apple_Utility_Counter = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Warehouse_ProduPlacabase_Apple = new javax.swing.JLabel();
        Warehouse_ProduCPU_Apple = new javax.swing.JLabel();
        Warehouse_ProdumemoRAM_Apple = new javax.swing.JLabel();
        Warehouse_FuenteAlimen_Apple = new javax.swing.JLabel();
        Wrehouse_TarjeGrafi_Apple = new javax.swing.JLabel();
        Warehouse_Ensambla_Apple = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Const_ProduPlaca_MSI = new javax.swing.JSpinner();
        Const_ProduCPU_MSI = new javax.swing.JSpinner();
        Const_ProduMemoRAM_MSI = new javax.swing.JSpinner();
        Const_ProduFuenteAlime_MSI = new javax.swing.JSpinner();
        Const_ProduTarjegGraf_MSI = new javax.swing.JSpinner();
        Const_Ensambladores_MSI = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        MSI_Deadline_Counter = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        MSI_Gain_Counter = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        MSI_Loss_Counter = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        MSI_Utility_Counter = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        MSI_Fail_Counter = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        MSI_Discount_Counter = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        Warehouse_ProduPlacabase_MSI = new javax.swing.JLabel();
        Warehouse_ProduCPU_MSI = new javax.swing.JLabel();
        Warehouse_ProdumemoRAM_MSI = new javax.swing.JLabel();
        Warehouse_FuenteAlimen_MSI = new javax.swing.JLabel();
        Wrehouse_TarjeGrafi_MSI = new javax.swing.JLabel();
        Warehouse_Ensambla_MSI = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.setBackground(new java.awt.Color(214, 189, 162));

        saveButtonActionPerformed.setBackground(new java.awt.Color(132, 92, 71));
        saveButtonActionPerformed.setForeground(new java.awt.Color(255, 255, 255));
        saveButtonActionPerformed.setText("Guardar");
        saveButtonActionPerformed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformedActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(132, 92, 71));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("INICIAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel34.setText("Deadline");

        jLabel35.setText("Duracion del día");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(375, 375, 375)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addComponent(saveButtonActionPerformed, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(444, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(301, 301, 301)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel34)
                    .addComponent(Cont_Deadline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Cont_Day_Duration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(511, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel35)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(jLabel35))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cont_Deadline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cont_Day_Duration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 201, Short.MAX_VALUE)
                .addComponent(saveButtonActionPerformed)
                .addGap(62, 62, 62))
        );

        jTabbedPane1.addTab("Inicio", jPanel2);

        Apple_Director_State.setText("Trabajando");

        Apple_Pm_State.setText("Trabajando");

        jLabel5.setText("Faltas (PM)");

        Apple_Fail_Counter.setText("0");

        jLabel7.setText("Sueldo descontado");

        Apple_Discount_Counter.setText("0");

        jLabel9.setText("Project Manager");

        jLabel10.setText("Director");

        jLabel11.setFont(new java.awt.Font("AppleGothic", 0, 13)); // NOI18N
        jLabel11.setText("Deadline");

        Apple_Deadline_Counter.setFont(new java.awt.Font("AppleGothic", 0, 13)); // NOI18N
        Apple_Deadline_Counter.setText("0");

        jLabel13.setFont(new java.awt.Font("AppleGothic", 0, 13)); // NOI18N
        jLabel13.setText("Ganancias");

        Apple_Gain_Counter.setText("0");

        jLabel15.setFont(new java.awt.Font("AppleGothic", 0, 13)); // NOI18N
        jLabel15.setText("Gastos");

        Apple_Loss_Counter.setText("0");

        jLabel17.setFont(new java.awt.Font("AppleGothic", 0, 13)); // NOI18N
        jLabel17.setText("Utilidad");

        Apple_Utility_Counter.setText("0");

        jLabel4.setText("Productores de placa base");

        jLabel6.setText("Productores de CPUs");

        jLabel8.setText("Productores de Memoria RAM");

        jLabel14.setText("Productores de Fuente de alimentación");

        jLabel16.setText("Productores de tarjetas gráficas");

        jLabel18.setText("Ensambladores");

        Warehouse_ProduPlacabase_Apple.setText("0");

        Warehouse_ProduCPU_Apple.setText("0");

        Warehouse_ProdumemoRAM_Apple.setText("0");

        Warehouse_FuenteAlimen_Apple.setText("0");

        Wrehouse_TarjeGrafi_Apple.setText("0");

        Warehouse_Ensambla_Apple.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(32, 32, 32)
                                    .addComponent(jLabel11)
                                    .addGap(40, 40, 40)
                                    .addComponent(Apple_Deadline_Counter))
                                .addComponent(jLabel9)
                                .addComponent(jLabel7))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                    .addGap(41, 41, 41)
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Apple_Gain_Counter)
                                    .addGap(161, 161, 161))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addGap(220, 220, 220))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                    .addComponent(jLabel15)
                                                    .addGap(92, 92, 92)
                                                    .addComponent(Apple_Loss_Counter))
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                    .addComponent(jLabel18)
                                                    .addGap(84, 84, 84)))
                                            .addGap(85, 85, 85)
                                            .addComponent(jLabel17)
                                            .addGap(73, 73, 73))))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Apple_Pm_State)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addGap(152, 152, 152)
                                    .addComponent(Apple_Director_State)))
                            .addGap(99, 99, 99)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel8)
                                .addComponent(jLabel14)
                                .addComponent(jLabel16))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Const_ProduMemoRAM_Apple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Const_ProduCPU_Apple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Const_ProduPlaca_Apple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Const_ProduFuenteAlime_Apple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Const_ProduTarjegGraf_Apple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Const_Ensambladores_Apple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(21, 21, 21)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(155, 155, 155)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Apple_Discount_Counter)
                            .addComponent(Apple_Fail_Counter))
                        .addGap(537, 537, 537)))
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Warehouse_ProduPlacabase_Apple)
                    .addComponent(Apple_Utility_Counter)
                    .addComponent(Warehouse_ProduCPU_Apple)
                    .addComponent(Warehouse_ProdumemoRAM_Apple)
                    .addComponent(Warehouse_FuenteAlimen_Apple)
                    .addComponent(Wrehouse_TarjeGrafi_Apple)
                    .addComponent(Warehouse_Ensambla_Apple))
                .addGap(94, 94, 94))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(Apple_Deadline_Counter)
                    .addComponent(jLabel13)
                    .addComponent(Apple_Gain_Counter)
                    .addComponent(jLabel15)
                    .addComponent(Apple_Loss_Counter)
                    .addComponent(jLabel17)
                    .addComponent(Apple_Utility_Counter))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Const_ProduCPU_Apple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(Warehouse_ProduCPU_Apple)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(Const_ProduPlaca_Apple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Warehouse_ProduPlacabase_Apple))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(Apple_Director_State))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(Apple_Pm_State))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Const_ProduMemoRAM_Apple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(Warehouse_ProdumemoRAM_Apple)))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Const_ProduFuenteAlime_Apple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(Warehouse_FuenteAlimen_Apple))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Apple_Fail_Counter))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(4, 4, 4)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Apple_Discount_Counter)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Const_ProduTarjegGraf_Apple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Wrehouse_TarjeGrafi_Apple))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Const_Ensambladores_Apple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(Warehouse_Ensambla_Apple))))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        Cont_Guionista_CN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Cont_Guionista_CN.setEditor(new javax.swing.JSpinner.NumberEditor(Cont_Guionista_CN, ""));

        Cont_Guionista_CN.setValue(1);

        Cont_Guionista_CN.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Cont_Guionista_CNStateChanged(evt);
            }
        });

        Cartoon.add(Cont_Guionista_CN, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 80, 20));

        jTabbedPane1.addTab("Apple", jPanel3);

        jLabel12.setFont(new java.awt.Font("AppleGothic", 0, 13)); // NOI18N
        jLabel12.setText("Deadline");

        MSI_Deadline_Counter.setText("0");

        jLabel20.setFont(new java.awt.Font("AppleGothic", 0, 13)); // NOI18N
        jLabel20.setText("Ganancias");

        MSI_Gain_Counter.setText("0");

        jLabel22.setFont(new java.awt.Font("AppleGothic", 0, 13)); // NOI18N
        jLabel22.setText("Gastos");

        MSI_Loss_Counter.setText("0");

        jLabel24.setFont(new java.awt.Font("AppleGothic", 0, 13)); // NOI18N
        jLabel24.setText("Utilidad");

        MSI_Utility_Counter.setText("0");

        jLabel19.setText("Director");

        jLabel26.setText("Project Manager");

        jLabel27.setText("Trabajando");

        jLabel28.setText("Trabajando");

        jLabel29.setText("Faltas (PM)");

        MSI_Fail_Counter.setText("0");

        jLabel31.setText("Sueldo descontado");

        MSI_Discount_Counter.setText("0");

        jLabel21.setText("Productores de placa base");

        jLabel23.setText("Productores de CPUs");

        jLabel25.setText("Productores de Memoria RAM");

        jLabel30.setText("Productores de Fuente de alimentación");

        jLabel32.setText("Productores de tarjetas gráficas");

        jLabel33.setText("Ensambladores");

        Warehouse_ProduPlacabase_MSI.setText("0");

        Warehouse_ProduCPU_MSI.setText("0");

        Warehouse_ProdumemoRAM_MSI.setText("0");

        Warehouse_FuenteAlimen_MSI.setText("0");

        Wrehouse_TarjeGrafi_MSI.setText("0");

        Warehouse_Ensambla_MSI.setText("0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel28)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(43, 43, 43)
                                .addComponent(MSI_Deadline_Counter)
                                .addGap(67, 67, 67)
                                .addComponent(jLabel20)
                                .addGap(90, 90, 90)
                                .addComponent(MSI_Gain_Counter))
                            .addComponent(jLabel27)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(jLabel19)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel31))
                                .addGap(107, 107, 107)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(MSI_Discount_Counter)
                                    .addComponent(MSI_Fail_Counter))))))
                .addGap(100, 100, 100)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(91, 91, 91)
                        .addComponent(MSI_Loss_Counter)
                        .addGap(91, 91, 91)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MSI_Utility_Counter)
                        .addGap(55, 55, 55))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel33)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Const_Ensambladores_MSI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel32)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Const_ProduTarjegGraf_MSI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Const_ProduMemoRAM_MSI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel30))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(83, 83, 83)
                                        .addComponent(Const_ProduPlaca_MSI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Const_ProduFuenteAlime_MSI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Const_ProduCPU_MSI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(66, 66, 66)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Warehouse_ProduPlacabase_MSI)
                            .addComponent(Warehouse_ProduCPU_MSI)
                            .addComponent(Warehouse_ProdumemoRAM_MSI)
                            .addComponent(Warehouse_FuenteAlimen_MSI)
                            .addComponent(Wrehouse_TarjeGrafi_MSI)
                            .addComponent(Warehouse_Ensambla_MSI))
                        .addGap(0, 65, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel28))
                .addGap(41, 41, 41)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(MSI_Fail_Counter))
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(MSI_Discount_Counter))
                .addContainerGap(130, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(MSI_Deadline_Counter)
                    .addComponent(jLabel20)
                    .addComponent(MSI_Gain_Counter)
                    .addComponent(jLabel22)
                    .addComponent(MSI_Loss_Counter)
                    .addComponent(jLabel24)
                    .addComponent(MSI_Utility_Counter))
                .addGap(105, 105, 105)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(Const_ProduPlaca_MSI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Warehouse_ProduPlacabase_MSI))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(Const_ProduCPU_MSI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Warehouse_ProduCPU_MSI))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(Const_ProduMemoRAM_MSI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Warehouse_ProdumemoRAM_MSI))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(Const_ProduFuenteAlime_MSI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Warehouse_FuenteAlimen_MSI))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(Const_ProduTarjegGraf_MSI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Wrehouse_TarjeGrafi_MSI))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(Const_Ensambladores_MSI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Warehouse_Ensambla_MSI))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("MSI", jPanel4);

        jLabel1.setFont(new java.awt.Font("AppleGothic", 1, 36)); // NOI18N
        jLabel1.setText("Gráfico");

        jLabel2.setFont(new java.awt.Font("AppleGothic", 0, 13)); // NOI18N
        jLabel2.setText("MSI");

        jLabel3.setFont(new java.awt.Font("AppleGothic", 0, 13)); // NOI18N
        jLabel3.setText("Apple");

        jPanel6.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(115, 185, 123));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(365, 365, 365)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 376, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(423, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Gráfico", jPanel5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformedActionPerformed
        // TODO add your handling code here:
        
          if(iniciado == true){
            //Apple
            int placaApple=(int) this.Const_ProduPlaca_Apple.getValue();
            int cpuApple=(int) this.Const_ProduCPU_Apple.getValue();
            int ramApple=(int) this.Const_ProduMemoRAM_Apple.getValue();
            int fuenteAlimeApple=(int) this.Const_ProduFuenteAlime_Apple.getValue();
            int tarjeGrafApple=(int) this.Const_ProduTarjegGraf_Apple.getValue();
            int EnsambladoresApple=(int) this.Const_Ensambladores_Apple.getValue();
            //MSI
             int placaMSI=(int) this.Const_ProduPlaca_MSI.getValue();
            int cpuMSI=(int) this.Const_ProduCPU_MSI.getValue();
            int ramMSI=(int) this.Const_ProduMemoRAM_MSI.getValue();
            int fuenteAlimeMSI=(int) this.Const_ProduFuenteAlime_MSI.getValue();
            int tarjeGrafMSI=(int) this.Const_ProduTarjegGraf_MSI.getValue();
            int EnsambladoresMSI=(int) this.Const_Ensambladores_MSI.getValue();
            
            int deadline=(int) this.Cont_Deadline.getValue();
            int DuracionD=(int) this.Cont_Day_Duration.getValue();
          
            
             String TodoTXT="Duracion\n"+DuracionD+";\nDeadline\n"+deadline+";\nApple-\nTrabajadores:\nProductoresPlaca,"+placaApple+
                    "\ncpu,"+cpuApple+"\nram,"+ramApple+"\nFuenteAlimentacion,"+fuenteAlimeApple+"\nTarjetagrafica,"+tarjeGrafApple+"\nensambladores,"+EnsambladoresApple+";\n"
                    + "MSI-\nTrabajadores:\nProductoresPlaca,"+placaMSI+
                    "\ncpu,"+cpuMSI+"\nram,"+ramMSI+"\nFuenteAlimentacion,"+fuenteAlimeMSI+"\nTarjetagrafica,"+tarjeGrafMSI+"\nensambladores,"+EnsambladoresMSI;
            
//            System.out.println(TodoTXT);
            
            try {
            if(getPath()!=null) {
            PrintWriter pw=new PrintWriter(getPath());
            pw.print(TodoTXT);
            pw.close();
            JOptionPane.showMessageDialog(null, "Guardado exitoso");
            System.exit(0);
            }
            else{JOptionPane.showMessageDialog(null, "Error!! Primero debe cargar un archivo txt");}
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error!!!!!");
            System.exit(0);
        } 
        
        }else{
            JOptionPane.showMessageDialog(null,"La simulación no ha empezado todavía, no se puede guardar");
        }
                                              
        
    }//GEN-LAST:event_saveButtonActionPerformedActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
                // TODO add your handling code here:
        
        //    //se lee el txt
    if (iniciado==false){
        iniciado=true;
    JFileChooser file = new JFileChooser();
    FileNameExtensionFilter filter = new FileNameExtensionFilter(".TXT","txt");
    file.setFileSelectionMode(JFileChooser.FILES_ONLY);
    file.setFileFilter(filter);
    int selection=file.showOpenDialog(this);
    
    if(selection==JFileChooser.APPROVE_OPTION) {
        File archive=file.getSelectedFile(); 
        String path=archive.getAbsolutePath();
        setPath(path);
    
        if(!path.contains("txt")) {
        JOptionPane.showMessageDialog(null, "Por favor elija un archivo del tipo txt");
        }
        else {
        try{
            File archivo = new File (path);
            FileReader fr = new FileReader(archivo); 
            BufferedReader br = new BufferedReader(fr); 
                 
            String cadena;
            String complete=""; 
      
            while ((cadena=br.readLine())!=null) { //lee hasta llegar a null que significa que se acabo el archivo

                if(!cadena.isEmpty()&& !cadena.isBlank()) { //revisa que la linea no sea vacia/que el tamaño de la cadena sea 0
                    complete+=cadena+"\n";
                }
            }
                
            fr.close();
            br.close();
            complete=complete.trim(); //quita linea en blanco al final
            //el !"".equals es para verificar que el string no sea solo un espacio en blanco
            if(!"".equals(complete)) {
                String[] info;
                String [] todo=complete.split(";");
                String [] Dias=todo[0].split("\n");
                int duracionDias=Integer.parseInt(Dias[1]);
                if(duracionDias<=0) {
                    throw new Exception("La duracion del dia no puede ser 0");
                }
                this.Cont_Day_Duration.setValue(duracionDias);
                //System.out.println(duracionDias); //todo bien aqui
                String[] Diasdead=todo[1].split("\n");
                //System.out.println(Diasdead[1]);
                int Deadline=Integer.parseInt(Diasdead[2]);
                if(Deadline<=0) {
                    throw new Exception("El tiempo de entrega no puede ser 0");
                }
                this.Cont_Deadline.setValue(Deadline);
                getApple_Deadline_Counter().setText(Integer.toString(Deadline));
                getMSI_Deadline_Counter().setText(Integer.toString(Deadline));
                
                //ya tengo la duracion del dia y la deadline se crean/agregan las cosas
                MSI.setDayDuration(duracionDias);
                Apple.setDayDuration(duracionDias);
                MSI.setDeliveryDay(Deadline);
                Apple.setDeliveryDay(Deadline);
                
                MSI.getWarehouse().setDeadlineCounter(Deadline);
                MSI.getWarehouse().setDeadline(Deadline);
                
                Apple.getWarehouse().setDeadlineCounter(Deadline);
                Apple.getWarehouse().setDeadline(Deadline);
                
                ProjectManager MSIpm=new ProjectManager(40,duracionDias,Global.getMutexMSI(),MSI.getWarehouse());
                Supervisor MSISuper = new Supervisor(60,Global.getMutexMSI(),duracionDias,MSI.getWarehouse(), MSIpm);
                ProjectManager Applepm=new ProjectManager(40,duracionDias,Global. getMutexApple(),Apple.getWarehouse());
                Supervisor AppleSuper = new Supervisor(60,Global.getMutexApple(),duracionDias,Apple.getWarehouse(),Applepm) ;
                
               //todo2 tiene cosas de cartoon
                todo[2]=todo[2].trim();
                String [] infoestu1=todo[2].split("-");
                //todo3 tiene cosas de nick
                todo[3]=todo[3].trim();
                String [] infoestu2=todo[3].split("-");
                
                if (infoestu1[0].compareTo("Apple")==0) { //el if es porsia 
//                     System.out.println("jajajaj "+infoestu1[0]);
//                     System.out.println(infoestu1[1]);
                     infoestu1[1]=infoestu1[1].trim();
                     String [] divTra=infoestu1[1].split(":");
                     divTra[1]=divTra[1].trim();
                     String [] trabajadores=divTra[1].split("\n");
                     
                     for (int i = 0; i < trabajadores.length; i++) {
                         //System.out.println(i+" "+trabajadores[i]);
                         String [] cantidad=trabajadores[i].split(",");
                         //cantidad[0] debe tener el nombre del trabajador y el [1] la cantidad de ese tipo
                         //cuando se vaya a crear el dev le paso i que seria el tipo y cantidad[1] que seria la cantidad
                         //System.out.println(cantidad[1]);
                         if(Integer.parseInt(cantidad[1])>0) {
                            Apple.AddWorker(i,Integer.parseInt(cantidad[1]));
                         }else {
                         throw new Exception("La cantidad de trabajadores no puede ser 0");
                         }
                         
                     }
                    if(Apple.getListMotherboard().getSize()+Apple.getListCPU().getSize()+Apple.getListRAM().getSize()+Apple.getListPowerSupply().getSize()+Apple.getListGraphic().getSize()+Apple.getListAssembler().getSize()>12){
                        throw new Exception("La cantidad de trabajadores no puede ser 0");
                    }
                    Applepm.start();
                    AppleSuper.start();
                    System.out.println("Listo apple");
                    this.Const_ProduPlaca_Apple.setValue(Apple.getListMotherboard().getSize());
                    this.Const_ProduCPU_Apple.setValue(Apple.getListCPU().getSize());
                    this.Const_ProduMemoRAM_Apple.setValue(Apple.getListRAM().getSize());
                    this.Const_ProduFuenteAlime_Apple.setValue(Apple.getListPowerSupply().getSize());
                    this.Const_ProduTarjegGraf_Apple.setValue(Apple.getListGraphic().getSize());
                    this.Const_Ensambladores_Apple.setValue(Apple.getListAssembler().getSize());
                 
                 }
                 else if (infoestu1[0].compareTo("MSI")==0) {
                     infoestu1[1]=infoestu1[1].trim();
                     String [] divTra=infoestu1[1].split(":");
                     divTra[1]=divTra[1].trim();
                     String [] trabajadores=divTra[1].split("\n");
                     
                     for (int i = 0; i < trabajadores.length; i++) {
                         //System.out.println(i+" "+trabajadores[i]);
                         String [] cantidad=trabajadores[i].split(",");
                         //cantidad[0] debe tener el nombre del trabajador y el [1] la cantidad de ese tipo
                         //cuando se vaya a crear el dev le paso i que seria el tipo y cantidad[1] que seria la cantidad
                         //System.out.println(cantidad[1]);
                         if(Integer.parseInt(cantidad[1])>0) {
                            MSI.AddWorker(i,Integer.parseInt(cantidad[1]));
                         } else {
                         throw new Exception("La cantidad de trabajadores no puede ser 0");
                         }
                         
                    }
                    MSIpm.start();
                    MSISuper.start(); 
                    this.Const_ProduPlaca_MSI.setValue(MSI.getListMotherboard().getSize());
                    this.Const_ProduCPU_MSI.setValue(MSI.getListCPU().getSize());
                    this.Const_ProduMemoRAM_MSI.setValue(MSI.getListRAM().getSize());
                    this.Const_ProduFuenteAlime_MSI.setValue(MSI.getListPowerSupply().getSize());
                    this.Const_ProduTarjegGraf_MSI.setValue(MSI.getListGraphic().getSize());
                    this.Const_Ensambladores_MSI.setValue(MSI.getListAssembler().getSize());
                    
                 }
                 
                 if (infoestu2[0].compareTo("Apple")==0) {
//                     System.out.println("jejejeje "+infoestu2[0]);
//                     System.out.println(infoestu2[1]);
                     infoestu1[1]=infoestu1[1].trim();
                     String [] divTra=infoestu1[1].split(":");
                     divTra[1]=divTra[1].trim();
                     String [] trabajadores=divTra[1].split("\n");
                     
                     for (int i = 0; i < trabajadores.length; i++) {
                         //System.out.println(i+" "+trabajadores[i]);
                         String [] cantidad=trabajadores[i].split(",");
                         //cantidad[0] debe tener el nombre del trabajador y el [1] la cantidad de ese tipo
                         //cuando se vaya a crear el dev le paso i que seria el tipo y cantidad[1] que seria la cantidad
                         //System.out.println(cantidad[1]);
                         if(Integer.parseInt(cantidad[1])>0) { 
                         Apple.AddWorker(i, Integer.parseInt(cantidad[1]));
                        }else {
                         throw new Exception("La cantidad de trabajadores no puede ser 0");
                         }
                         
                     }
                    Applepm.start();
                    AppleSuper.start(); 
                    this.Const_ProduPlaca_Apple.setValue(Apple.getListMotherboard().getSize());
                    this.Const_ProduCPU_Apple.setValue(Apple.getListCPU().getSize());
                    this.Const_ProduMemoRAM_Apple.setValue(Apple.getListRAM().getSize());
                    this.Const_ProduFuenteAlime_Apple.setValue(Apple.getListPowerSupply().getSize());
                    this.Const_ProduTarjegGraf_Apple.setValue(Apple.getListGraphic().getSize());
                    this.Const_Ensambladores_Apple.setValue(Apple.getListAssembler().getSize());
                 }
                 else if (infoestu2[0].compareTo("MSI")==0) {
                     String [] divTra=infoestu2[1].split(":");
                     divTra[1]=divTra[1].trim();
                     String [] trabajadores=divTra[1].split("\n");
                     System.out.println(infoestu2[0]);
                     for (int i = 0; i < trabajadores.length; i++) {
                         //System.out.println(i+" "+trabajadores[i]);
                         String [] cantidad=trabajadores[i].split(",");
                         //cantidad[0] debe tener el nombre del trabajador y el [1] la cantidad de ese tipo
                         //cuando se vaya a crear el dev le paso i que seria el tipo y cantidad[1] que seria la cantidad
                         //System.out.println(cantidad[1]);
                         if(Integer.parseInt(cantidad[1])>0) {
                            MSI.AddWorker(i, Integer.parseInt(cantidad[1]));
                         }else {
                         throw new Exception("La cantidad de trabajadores no puede ser 0");
                         }
                         
                     }
                    if(MSI.getListMotherboard().getSize()+MSI.getListCPU().getSize()+MSI.getListRAM().getSize()+MSI.getListPowerSupply().getSize()+MSI.getListGraphic().getSize()+MSI.getListAssembler().getSize()>13){
                        throw new Exception("La cantidad de trabajadores no puede ser 0");
                    }
                    MSIpm.start();
                    MSISuper.start(); 
                    this.Const_ProduPlaca_MSI.setValue(MSI.getListMotherboard().getSize());
                    this.Const_ProduCPU_MSI.setValue(MSI.getListCPU().getSize());
                    this.Const_ProduMemoRAM_MSI.setValue(MSI.getListRAM().getSize());
                    this.Const_ProduFuenteAlime_MSI.setValue(MSI.getListPowerSupply().getSize());
                    this.Const_ProduTarjegGraf_MSI.setValue(MSI.getListGraphic().getSize());
                    this.Const_Ensambladores_MSI.setValue(MSI.getListAssembler().getSize());
                      
                      System.out.println("Listo MSI");
                 
                 
                 }
                 
                
//                for (int i = 0; i < todo.length; i++) {
//                  System.out.println(todo[i]);  
//                }
                
            
            }
                
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erorr!!!! Asegurate de haber cargado el archivo correcto");
            System.exit(0);
            }
        }
    // revisar despues
    //Aquí se crea todo el tema de la gráfica    
    // Global.addCn(0, 0);
    // Global.addNk(0, 0);
    // Global.addSeries(Global.getCn());
    // Global.addSeries(Global.getNk());
        
    //JFreeChart chart = ChartFactory.createXYLineChart("Utilidad vs Tiempo", "Utilidad (Millones $)", "Tiempo (Días)", Global.dataset, PlotOrientation.HORIZONTAL, false, true, false);
        
    //final XYPlot plot = chart.getXYPlot( );
        
   // ChartPanel barPanel = new ChartPanel(chart);
        
    //XYLineAndShapeRenderer renderer = new XYLineAndShapeRenderer( );
   // renderer.setSeriesPaint( 0 , Color.BLACK );
    //renderer.setSeriesPaint( 1 , Color.RED);
    //renderer.setSeriesStroke( 0 , new BasicStroke( 4.0f ) );
    //renderer.setSeriesStroke( 1 , new BasicStroke( 4.0f ) );
    //plot.setRenderer( renderer );

   // panelChart.removeAll();
    //panelChart.add(barPanel);
    //panelChart.validate();
    
    } else {
        JOptionPane.showMessageDialog(null, "ERROR");
        System.exit(0);
    }
    } else{
        JOptionPane.showMessageDialog(null, "La simulacion ya ha iniciado");
    }


                                  
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JLabel Apple_Deadline_Counter;
    private javax.swing.JLabel Apple_Director_State;
    private static javax.swing.JLabel Apple_Discount_Counter;
    private static javax.swing.JLabel Apple_Fail_Counter;
    private static javax.swing.JLabel Apple_Gain_Counter;
    private javax.swing.JLabel Apple_Loss_Counter;
    private javax.swing.JLabel Apple_Pm_State;
    private static javax.swing.JLabel Apple_Utility_Counter;
    private javax.swing.JSpinner Const_Ensambladores_Apple;
    private javax.swing.JSpinner Const_Ensambladores_MSI;
    private javax.swing.JSpinner Const_ProduCPU_Apple;
    private javax.swing.JSpinner Const_ProduCPU_MSI;
    private javax.swing.JSpinner Const_ProduFuenteAlime_Apple;
    private javax.swing.JSpinner Const_ProduFuenteAlime_MSI;
    private javax.swing.JSpinner Const_ProduMemoRAM_Apple;
    private javax.swing.JSpinner Const_ProduMemoRAM_MSI;
    private javax.swing.JSpinner Const_ProduPlaca_Apple;
    private javax.swing.JSpinner Const_ProduPlaca_MSI;
    private javax.swing.JSpinner Const_ProduTarjegGraf_Apple;
    private javax.swing.JSpinner Const_ProduTarjegGraf_MSI;
    private javax.swing.JSpinner Cont_Day_Duration;
    private javax.swing.JSpinner Cont_Deadline;
    private static javax.swing.JLabel MSI_Deadline_Counter;
    private static javax.swing.JLabel MSI_Discount_Counter;
    private static javax.swing.JLabel MSI_Fail_Counter;
    private static javax.swing.JLabel MSI_Gain_Counter;
    private static javax.swing.JLabel MSI_Loss_Counter;
    private static javax.swing.JLabel MSI_Utility_Counter;
    private javax.swing.JLabel Warehouse_Ensambla_Apple;
    private static javax.swing.JLabel Warehouse_Ensambla_MSI;
    private javax.swing.JLabel Warehouse_FuenteAlimen_Apple;
    private static javax.swing.JLabel Warehouse_FuenteAlimen_MSI;
    private javax.swing.JLabel Warehouse_ProduCPU_Apple;
    private static javax.swing.JLabel Warehouse_ProduCPU_MSI;
    private javax.swing.JLabel Warehouse_ProduPlacabase_Apple;
    private static javax.swing.JLabel Warehouse_ProduPlacabase_MSI;
    private javax.swing.JLabel Warehouse_ProdumemoRAM_Apple;
    private static javax.swing.JLabel Warehouse_ProdumemoRAM_MSI;
    private javax.swing.JLabel Wrehouse_TarjeGrafi_Apple;
    private static javax.swing.JLabel Wrehouse_TarjeGrafi_MSI;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private static javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton saveButtonActionPerformed;
    // End of variables declaration//GEN-END:variables
}
